services:
  bot:
    image: ywsj/tg-group-guard:latest
    container_name: tg-group-guard
    restart: unless-stopped
    ports:
      - "8181:8080"
    volumes:
      - ./data:/data
    env_file:
      - .env
